### ISSUE TITLE
Jitsi Meet Videoconference Platform Segfaults FireFox

### ISSUE THREAD

**Issue by nerdcorenet** [FuriLabs/furios-firefox-tweaks#1]
I seem unable to join any Jitsi Meet at https://meet.jit.si/ using FireFox on FuriOS on a FLX1 device. Upon joining the videoconference, FireFox segfaults.

**Comment by GranPC** [comment]
Hi there, we believe this should be fixed in the latest staging release, which should land in production in a few days should everything go well.

**Comment by GranPC** [comment]
Just gave this specific use-case a shot. Looks good!
![Screenshot_2024-08-06_20-27-18](https://github.com/user-attachments/assets/a87caea4-08d9-437a-b34f-7e9c5e8efd02)

**Comment by GranPC** [comment]
And this just hit prod! @nerdcorenet, can you still repro?

**Comment by GranPC** [comment]
Closing for now since I am pretty confident about it being fixed. Feel free to reopen if it's still an issue!
